[colors]
foreground = "#eef1f8"
background = "#07080d"
cursor_fg = "#eef1f8"
cursor_bg = "#07080d"
cursor_border = "#eef1f8"
selection_fg = "#07080d"
selection_bg = "#c4c6cd"
ansi = [
  "#07080d", # Black
  "#590008", # Red
  "#005523", # Green
  "#6b5300", # Yellow
  "#004c73", # Blue
  "#470045", # Magenta
  "#007373", # Cyan
  "#eef1f8", # White
]
brights = [
  "#14161b", # Bright Black
  "#ffc0b9", # Bright Red
  "#b3f6c0", # Bright Green
  "#fce094", # Bright Yellow
  "#a6dbff", # Bright Blue
  "#ffcaff", # Bright Magenta
  "#8cf8f7", # Bright Cyan
  "#9b9ea4", # Bright White
]

[metadata]
name = 'Neovim'
